baseURL: https://op-y.github.io
languageCode: en-us
defaultContentLanguage: en
title: Qin的自习室
theme: cupper-hugo-theme
enableGitInfo: false

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Qin的自习室：记录学习点点滴滴的地方。
  homeMetaContent: Qin的自习室。
  footer: Powered by [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: Qin
  katex: true

menu:
  nav:
    - name: Qin
      url: /
      weight: 1
    - name: 分享文章
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: 关于自习室
      url: /about/
      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
